a=input('Enter any sentence')
b=int(a)
print('Value of b =',b,type(b),sep='\n')
c=float(a)
print('Value of c =',c,type(c),sep='\n')
d=str(a)
print('Value of d =',d,type(d),sep='\n')
e=complex(a)
print('Value of e =',e,type(e),sep='\n')
f=bool(a)
print('Value of f =',f,type(f),sep='\n')
