s1=input('Enter a string 1: ')
s2=input('Enter a string 2: ')
s3=input('Enter a string 3: ')
print('Length of string 1 is ', len(s1))
print(s2[2:5])
print(s3[1:])
print(s3[:6])
print(s2.lower())
print(s3.upper())
print(s1+s2+s3)
print(3*s2)
